---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
zipFilename='activity.zip'
dataFilename='activity.csv'
if (!file.exists(dataFilename)) {
	unzip(zipFilename,dataFilename)
}
data=read.csv(dataFilename,colClasses=c('integer','Date','integer'))
```


## What is mean total number of steps taken per day?

```{r message=FALSE}
library(dplyr)
```
```{r}
stepsPerDay = (
	data %>% 
	group_by(date) %>% 
	summarize(steps=sum(steps))
)$steps
hist(stepsPerDay)
```

Distribution of total steps per day has mean `r format(mean(stepsPerDay,na.rm=T))` and median `r format(median(stepsPerDay,na.rm=T))`.


## What is the average daily activity pattern?

```{r}
intervalData = data %>%
	group_by(interval) %>%
	summarize(steps=mean(steps,na.rm=T))
plot(intervalData,type='l',main='Average number of steps per interval')
```


## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
